#!/bin/sh
# Prio: 1

. /usr/src/openapp-backup/includes/index

###
# This script will backup and restore the software installed via dpkg

BACKUPDIR=$1
ACTION=$2

run_backup() {
    dpkg --get-selections > ${BACKUPDIR}/dpkg-selections || fatal "Could not run dpkg-selections"
}

case ${ACTION} in
    backup)
        run_backup
    ;;
    restore)
        echo "Not implemented"
    ;;
esac
