#!/bin/bash
# Prio: 100

. /usr/lib/openapp-backup/includes/index

###
# This script will backup and restore /home

BACKUPDIR=$1
ACTION=$2

run_backup() {
    rsync -a /home ${BACKUPDIR} || fatal "Could not rsync /home to ${BACKUPDIR}"
}

run_restore() {
    rsync -a ${BACKUPDIR}/home/ /home
}

case ${ACTION} in
    backup)
        run_backup
    ;;
    restore)
        run_restore
    ;;
esac
