#!/bin/sh
# Prio: 1.1

. /usr/src/openapp-backup/includes/index

###
# This script will backup and restore all the mysql databases

BACKUPDIR=$1
ACTION=$2

run_backup() {
    MYSQLDUMPOPTS="--defaults-file=/etc/mysql/debian.cnf --add-drop-database --add-locks --all-databases --allow-keywords --create-options --disable-keys --events --extended-insert --lock-all-tables --quick --routines"
    mysqldump ${MYSQLDUMPOPTS} | gzip > ${BACKUPDIR}/mysqldump.sql.gz
}

case ${ACTION} in
    backup)
        run_backup
    ;;
    restore)
        echo "Not implemented"
    ;;
esac
