#!/bin/bash
# Prio: 2

. /usr/lib/openapp-backup/includes/index

###
# This script will backup and restore /var/www

BACKUPDIR=$1
ACTION=$2

run_backup() {
    rsync -a /var/www ${BACKUPDIR} || fatal "Could not rsync /var/www to ${BACKUPDIR}"
}

run_restore() {
    rsync -a --delete ${BACKUPDIR}/ /var
}

case ${ACTION} in
    backup)
        run_backup
    ;;
    restore)
        run_restore
    ;;
esac
