#!/bin/bash

###
# This script will look for scripts to run to create a backup of the system
# which should be suitable for restoring and migrating to another machine
###

. /usr/lib/openapp-backup/includes/index

[ `id -u` -gt 0 ]  && fatal "This script must be run as root"

function show_help() {
	echo "openapp-backup [-n|-t]"
	echo ""
	echo "-n : Only show which scripts you would run, don't actually do anything"
	echo "-t : Do not create an executable script. Just create the tar-file for openapp-restore"
	echo ""
	exit 1;
}

if [ ! -z $1 ]; then
	case "$1" in
	    -n)
			DRY_RUN=yes
		;;
	    -t)
			TAR_ONLY=yes
		;;
	    *)
			show_help
		;;
	esac
fi

[ -z $2 ] || show_help

[ -z ${DRY_RUN} ] && BACKUPDIR=$(mktemp -d)
BASEMODULES=/usr/lib/openapp-backup/modules
MODULEDIR=/etc/openapp-backup/scripts.d
WARNINGS=0
FATALS=0

EXTRACTSCRIPT_HEAD='#!/bin/sh

show_help() {
	echo "$0 [-n]"
	echo ""
	echo "-n : Only extract the tar-file from this script"
	echo ""
	echo "Default behaviour is to extract the tar file and run openapp-restore"
	echo "You must be root to run this script."
	exit 1;
}

if [ ! -z $1 ]; then
	[ "$1" = "-n" ] || show_help
	DRY_RUN=yes
fi

[ `id -u` -gt 0 ]  && show_help

[ -z ${DRY_RUN} ] && echo "deb http://download.openpanel.com/dev/ lenny main" >> /etc/apt/sources.list.d/openpanel.list
[ -z ${DRY_RUN} ] && apt-key adv --keyserver keyserver.stack.nl --recv-keys 4EAC69B9
[ -z ${DRY_RUN} ] && apt-get update
[ -z ${DRY_RUN} ] && apt-get install openapp-backup

skip_lines=$(grep -an "^#ENDOFSCRIPT" "${0}" | cut -f 1 -d :)
skip_lines=$(($skip_lines+1))

';

EXTRACTSCRIPT_TAIL='
[ -z ${DRY_RUN} ] && BACKUPDIR=$(mktemp -d)
[ -z ${DRY_RUN} ] || BACKUPDIR=./
tail -n +${skip_lines} "${0}" > ${BACKUPDIR}/openapp-backup.tar.gz
MD5S=$(md5sum ${BACKUPDIR}/openapp-backup.tar.gz | cut -f 1 -d " ")

if [ "${MD5S}" != "${tarmd5}" ]; then
	echo "tar file is damaged"
	exit 1
fi

[ -z ${DRY_RUN} ] && openapp-restore ${BACKUPDIR}/openapp-backup.tar.gz
[ -z ${DRY_RUN} ] || echo "Only extracted the tar file. You can use it manually with openapp-restore"
exit 0

#ENDOFSCRIPT'


###
# Now look for specific modules to backup
MODULES=$(grep -H '^# Prio' "${MODULEDIR}"/* 2> /dev/null | sort -k 3 -n | cut -f 1 -d :)

[ -z "${MODULES}" ] && echo "No configured modules found in ${MODULEDIR}, running all modules in ${BASEMODULES}"
[ -z "${MODULES}" ] && MODULES=$(grep -H '^# Prio' "${BASEMODULES}"/* 2> /dev/null | sort -k 3 -n | cut -f 1 -d :)

for SCRIPT in $MODULES; do
    echo "Running ${SCRIPT}"
    SCRIPTNAME=$(basename ${SCRIPT})
	[ -z ${DRY_RUN} ] && mkdir -p ${BACKUPDIR}/${SCRIPTNAME}
    [ -z ${DRY_RUN} ] && OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} backup 2> /dev/null)
    [ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
done

[ -z ${DRY_RUN} ] || exit 0;

if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
    echo "All went well"
    echo "Creating tar-file"
    cd ${BACKUPDIR}
    tar --numeric-owner -zcf /tmp/openapp-backup.tar.gz . || warning "Could not create tar file"

    rm -rf ${BACKUPDIR};
    if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
		[ -z ${TAR_ONLY} ] && echo "${EXTRACTSCRIPT_HEAD}" > /tmp/openapp-backup.sh
		[ -z ${TAR_ONLY} ] && MD5S=$(md5sum /tmp/openapp-backup.tar.gz | cut -f 1 -d ' ')
		[ -z ${TAR_ONLY} ] && echo "tarmd5=$MD5S" >> /tmp/openapp-backup.sh
		[ -z ${TAR_ONLY} ] && echo "${EXTRACTSCRIPT_TAIL}" >> /tmp/openapp-backup.sh

		[ -z ${TAR_ONLY} ] && cat /tmp/openapp-backup.tar.gz >> /tmp/openapp-backup.sh
		[ -z ${TAR_ONLY} ] && chmod +x /tmp/openapp-backup.sh
        [ -z ${TAR_ONLY} ] && echo "Your backupfile is: /tmp/openapp-backup.sh"
		[ -z ${TAR_ONLY} ] && echo "You should execute it on your destination box"
		[ -z ${TAR_ONLY} ] || echo "Your backupfile is: //tmp/openapp-backup.tar.gz"
		[ -z ${TAR_ONLY} ] || echo "You can use it with openapp-restore"
    else
        echo "Something went wrong while creating the tar file. Please investigate"
        exit 1
    fi
else
    echo "There where $FATALS fatal errors and $WARNINGS warnings"
    exit 1
fi


