#!/bin/bash

###
# This script will look for scripts to run to create a backup of the system
# which should be suitable for restoring and migrating to another machine
###

. /usr/lib/openapp-backup/includes/index

[ `id -u` -gt 0 ]  && fatal "This script must be run as root"

function show_help() {
	echo "openapp-backup [-n]"
	echo ""
	echo "-n : Only show which scripts you would run, don't actually do anything"
	echo ""
	exit 1;
}

if [ ! -z $1 ]; then
	[ "$1" = "-n" ] || show_help
	DRY_RUN=yes
fi

[ -z ${DRY_RUN} ] && BACKUPDIR=$(mktemp -d)
MODULEDIR=/usr/lib/openapp-backup/modules
WARNINGS=0
FATALS=0

###
# Now look for specific modules to backup
MODULES=$(grep -H '^# Prio' ${MODULEDIR}/* | sort -k 3 -n | cut -f 1 -d :)
for SCRIPT in $MODULES; do
    echo "Running ${SCRIPT}"
    SCRIPTNAME=$(basename ${SCRIPT})
	[ -z ${DRY_RUN} ] && mkdir -p ${BACKUPDIR}/${SCRIPTNAME}
    [ -z ${DRY_RUN} ] && OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} backup 2> /dev/null)
    [ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
done

[ -z ${DRY_RUN} ] || exit 0;

if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
    echo "All went well"
    echo "Creating tar-file"
    cd ${BACKUPDIR}
    tar --numeric-owner -zcf /tmp/openapp-backup.tar.gz . || warning "Could not create tar file"

    rm -rf ${BACKUPDIR};
    if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
        echo "Your backupfile is: /tmp/openapp-backup.tar.gz"
    else
        echo "Something went wrong while creating the tar file. Please investigate"
        exit 1
    fi
else
    echo "There where $FATALS fatal errors and $WARNINGS warnings"
    exit 1
fi
