#!/bin/bash

###
# This script will look for scripts to run to restore a system based on the
# backup-file created by openapp-backup.
###

. /usr/src/openapp-backup/includes/index

[ -z $1 ] && fatal "You should enter an argument, the file you want to restore from"
[ -f ${1} ] || fatal "Cannot find the file you want me to use to restore"

[ `id -u` -gt 0 ]  && fatal "This script must be run as root"

BACKUPDIR=$(mktemp -d)
MODULEDIR=/usr/src/openapp-backup/modules
WARNINGS=0
FATALS=0

###
# Extract the tar-file in the tempdir
cd ${BACKUPDIR}
tar --numeric-owner -zxf ${1}

###
# Now look for specific modules to backup
MODULES=$(grep -H '^# Prio' ${MODULEDIR}/* | sort -k 3 -n | cut -f 1 -d :)
for SCRIPT in $MODULES; do
    SCRIPTNAME=$(basename ${SCRIPT})
    ###
    # Don't run this script if the backup doesn't contain a dir for it.
    [ -d ${BACKUPDIR}/${SCRIPTNAME} ] || continue

    echo "Running ${SCRIPTNAME}..."
    OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)
    [ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
done

rm -rf ${BACKUPDIR}

if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
    echo "All went well"
else
    echo "There where $FATALS fatal errors and $WARNINGS warnings"
    exit 1
fi
