#!/bin/bash

###
# This script will look for scripts to run to restore a system based on the
# backup-file created by openapp-backup.
###

. /usr/lib/openapp-backup/includes/index

[ -z $1 ] && fatal "You should enter an argument, the file you want to restore from"
[ -f ${1} ] || fatal "Cannot find the file you want me to use to restore"

[ `id -u` -gt 0 ]  && fatal "This script must be run as root"

function show_help() {
	echo "openapp-restore filename"
	echo ""
	echo "filename : The openapp-backup archive you want to restore"
	echo ""
	exit 1;
}

BACKUPDIR=$(mktemp -d)
BASEMODULES=/usr/lib/openapp-backup/modules
MODULEDIR=/etc/openapp-backup/scripts.d
WARNINGS=0
FATALS=0

###
# Extract the tar-file in the tempdir
cd ${BACKUPDIR}
tar --numeric-owner -zxf ${1}

###
# Make sure we run these first
MODULES="${BASEMODULES}/dpkg-selections ${BASEMODULES}/etc"

###
# Now look for specific modules to restore from
MODULES="${MODULES} "$(grep -H '^# Prio' "${MODULEDIR}"/* 2>/dev/null | sort -k 3 -n | cut -f 1 -d :)
for SCRIPT in $MODULES; do
    SCRIPTNAME=$(basename ${SCRIPT})
    ###
    # Don't run this script if the backup doesn't contain a dir for it.
    [ -d ${BACKUPDIR}/${SCRIPTNAME} ] || continue


    echo "Running ${SCRIPTNAME}..."
    OUTPUT=$(${SCRIPT} ${BACKUPDIR}/${SCRIPTNAME} restore 2> /dev/null)

	###
	# After we ran etc (which restored the symlinks of the box we're restoring)
	# refresh the modulelist. This will cause dpkg and etc to run again, but
	# that's not really an issue.
	[ "${SCRIPTNAME}" = "etc" ] && MODULES=$(grep -H '^# Prio' "${MODULEDIR}"/* 2>/dev/null | sort -k 3 -n | cut -f 1 -d :)

    [ -z "${OUTPUT}" ] || warning "${SCRIPT}: $OUTPUT"
done

rm -rf ${BACKUPDIR}

if [ $WARNINGS -eq 0 -a $FATALS -eq 0 ]; then
    echo "All went well"
else
    echo "There where $FATALS fatal errors and $WARNINGS warnings"
    exit 1
fi
