.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OPENAPP-BACKUP 1 "July 15, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
openapp-backup \- Create a backup of your OpenApp box
.SH SYNOPSIS
.B openapp-backup [-n|-t]
.SH DESCRIPTION
This manual page documents briefly the
.B openapp-backup
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBopenapp-backup\fP is a program that creates a backup of your current
.br
machine. It produces a executable restore file which you can run on your
.br
freshly installed targetbox. It will then create a (somewhat) exact copy of
.br
this machine.
.br
.br
It creates this backup with the help of scripts it finds in
.br
/etc/openapp-backup/scripts.d. Each script placed/linked to in that directory
.br
will be run if openapp-backup is executed. For more info on how to create a
.br
script yourself, see openapp-backup-scripts(1).
.SH OPTIONS
This program accepts the following arguments:
.TP 6
-n
Don't actually create a backup, but show you which scripts would be executed
.TP
-t
Don't create an executable script. Just create the tar-file for openapp-restore
.SH SEE ALSO
openapp-backup-scripts(1) openapp-restore(1) openapp-backup-dismod(1)
.SH AUTHOR
openapp-backup was written by Mark Schouten.
.PP
This manual page was written by Mark Schouten <mark@tuxis.nl>, for the OpenApp
.br
project (and may be used by others).
