.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OPENAPP-BACKUP-ENMOD / OPENAPP-BACKUP-DISMOD 1 "July 15, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
openapp-backup-dismod \- Enable/disable modules for openapp-backup
.SH SYNOPSIS
.B openapp-backup-dismod <modulename>
.SH DESCRIPTION
This manual page documents briefly the
.B openapp-backup-dismod and openapp-backup-enmod
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBopenapp-backup-dismod\fP is a program that allows you to easily enable and
.br
disable modules for openapp-backup. It scans /usr/lib/openapp-backup/modules
.br
for files and gives you a list of modules that you can enable. You can enter
.br
the modulename that you want to enable/disable as an argument as well.
.br
(Easy for scripts)
.PP
.br
.br
.SH OPTIONS
This program has one optional argument:
.TP 12
modulename
The name of the module that you want to enable/disable
.SH SEE ALSO
openapp-backup(1)
.SH AUTHOR
These scripts are based on the scripts by Krzysztof Krzyzaniak for lighttpd,
.br
but were changed by Mark Schouten.
.PP
This manual page was written by Mark Schouten <mark@tuxis.nl>, for the OpenApp
.br
project (and may be used by others).
