.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH OPENAPP-RESTORE 1 "July 15, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
openapp-restore \- Restores your OpenApp box
.SH SYNOPSIS
.B openapp-restore <filename>
.SH DESCRIPTION
This manual page documents briefly the
.B openapp-restore
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBopenapp-restore\fP is a program that restores your original OpenApp-box,
.br
based on the restore-file that openapp-backup(1) created. openapp-restore
.br
assumes that you are running it on a freshly installed machine. \fBIT WILL DELETE
.br
AND/OR OVERWRITE EXISTING DATA IF YOU HAVE IT.\fP
.PP
It will always start by installing all the software you had on the original
.br
box. What it will do next depends on the original box. Please remember that
.br
\fBEXISTING DATA WILL BE DELETED\fP, probably in /home, /var/www and your databases.
.PP
BTW: Did I mention that openapp-restore will delete or overwrite your existing data?
.br
.br
.SH OPTIONS
This program has one required argument:
.TP 12
filename
The tar-file that came from openapp-backup
.SH SEE ALSO
openapp-restore-scripts(1) openapp-backup(1)
.SH AUTHOR
openapp-restore was written by Mark Schouten.
.PP
This manual page was written by Mark Schouten <mark@tuxis.nl>, for the OpenApp
.br
project (and may be used by others).
